# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4deb5609128ec7dc072c08245a5ca7c0"
application_url = "https://g-converted-hash-data.trycloudflare.com"
embedded = true
name = "first-test-app"
handle = "first-test-app-143"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aqeel-njs-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products,write_discounts,write_price_rules,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://g-converted-hash-data.trycloudflare.com/auth/callback",
  "https://g-converted-hash-data.trycloudflare.com/auth/shopify/callback",
  "https://g-converted-hash-data.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
