# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4deb5609128ec7dc072c08245a5ca7c0"
application_url = "https://affiliate-recognition-golf-myspace.trycloudflare.com"
embedded = true
name = "first-test-app"
handle = "first-test-app-143"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_product_listings,read_product_listings,read_orders,write_discounts"

[auth]
redirect_urls = [
  "https://affiliate-recognition-golf-myspace.trycloudflare.com/auth/callback",
  "https://affiliate-recognition-golf-myspace.trycloudflare.com/auth/shopify/callback",
  "https://affiliate-recognition-golf-myspace.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "aqeel-njs-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
