# query RunInput {
#   discountNode {
#     metafield(namespace: "$app:my-test-product-discount2", key: "function-configuration") {
#       value
#     }
#   }
# }
query RunInput {
  cart {
    lines {
      bundleDiscount: attribute(key: "_bundle_discount") {
        value
      }
      bundleType: attribute(key: "_bundle_type") {
        value
      }
      id
      merchandise {
        ... on ProductVariant {
          id

          product {
            id
            testMeta: metafield(namespace: "custom", key: "fixed_discount") {
              value
            }
          }
        }
      }
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
      }
      quantity
    }
  }
}
