# query RunInput {
#   discountNode {
#     metafield(namespace: "$app:my-test-product-discount2", key: "function-configuration") {
#       value
#     }
#   }
# }
query RunInput {
  cart {
    lines {
      attribute(key: "_bundle_discount") {
        key
        value
      }
      id
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
      }
      quantity
    }
  }
}
